config/routes.rb
Rails.application.routes.draw do
  
	resources :users, only: [:new, :create, :show, :index]
	resources :lists, only: [:new, :create, :edit, :update, :destroy]
	resources :tasks, only: [:new, :create, :edit, :update, :destroy]

	resources :sessions, only: [:create]

	get 'login', to: 'sessions#new'
	get 'logout', to: 'sessions#destroy'

	get 'done/:id', to: 'tasks#done', as: 'done'
	get 'in_progress/:id', to: 'tasks#in_progress', as: 'in_progress'
	get 'order_up/:id', to: 'tasks#order_up', as: 'order_up'
	get 'order_down/:id', to: 'tasks#order_down', as: 'order_down'
	get 'show_list_form/:id', to: 'users#show_list_form', as: 'show_list_form'

	root 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	validates :title, presence: true
	validates :title, format: { with: /\s*\S+\s*/ }

	belongs_to :user
	has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
	validates :title, presence: true
	validates :title, format: { with: /\s*\S+\s*/ }
	belongs_to :list

	default_scope { order(order: :asc) }

	def mark_done
		self.update_attribute(:done, true)
	end

	def mark_in_progress
		self.update_attribute(:done, false)
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :username, :presence => true, :uniqueness => true
	validates :password, length: { minimum: 6 }

	has_many :lists, dependent: :destroy
	has_many :tasks, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :require_valid_user!

	def current_user
		if !session[:user_id].blank?
			@user ||= User.find(session[:user_id])
		end
	end

	def require_valid_user!
		if current_user.nil?
			redirect_to login_path
			flash[:error] = 'Please, log in'
		end
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	respond_to :html
	respond_to :js

	def new
	end

	def create
		@list = List.new(list_params)

		if @list.save
			flash.clear
			respond_with(@list)
		else
			flash[:error] = @list.errors.full_messages
			render :_list_form_error
		end
	end

	def edit
		@list = List.find(params[:id])
	end

	def update
		@list = List.find(params[:id])

		if @list.update(list_params)
			flash.clear
			respond_with(@list)
		else
			flash[:error] = @list.errors.full_messages
			render :_edit_list_form_error
		end
	end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		respond_with(@list)
	end

	private

	def list_params
		params.require(:list).permit(:title, :user_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_valid_user!, except: [:destroy]

	def new
	end

	def create
		reset_session
		@user = User.find_by(username: session_params[:username])
		if @user && @user.authenticate(session_params[:password])
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:error] = 'Invalid username/password combination'
			redirect_to login_path
		end
	end

	def destroy
		reset_session
		redirect_to login_path
	end

	private

	def session_params
		params.require(:session).permit(:username, :password)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	respond_to :html
	respond_to :js

	def new
	end

	def create
		@task = Task.new(task_params)
		all_tasks = Task.where(list_id: @task.list_id)
		order_array = []

		all_tasks.each { |e|  order_array << e.order }
		@task.order = order_array.max.nil? ? 1 : order_array.max + 1

		if @task.save
			flash.clear
			respond_with(@task)
		else
			flash[:error] = @task.errors.full_messages
			render :_form_error
		end
	end
	
	def edit
		@task = Task.find(params[:id])
	end

	def update
		@task = Task.find(params[:id])

		if @task.update(task_params)
			flash.clear
			respond_with(@task)
		else
			flash[:error] = @task.errors.full_messages
			render :_edit_form_error
		end
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		respond_with(@task)
	end

	def done
		@task = Task.find(params[:id])
		@task.mark_done
	end

	def in_progress
		@task = Task.find(params[:id])
		@task.mark_in_progress
	end

	def order_up
		@task = Task.find(params[:id])
		all_tasks = Task.where(list_id: @task.list_id)

		unless all_tasks.count < 2 || all_tasks.first == @task 
			prev_task = all_tasks[all_tasks.index(@task) - 1]
			prev_task.order += 1
			prev_task.save!
			@task.order -= 1
			@task.save!
		end
	end
	
	def order_down
		@task = Task.find(params[:id])
		all_tasks = Task.where(list_id: @task.list_id)

		unless all_tasks.count < 2 || all_tasks.last == @task
			next_task = all_tasks[all_tasks.index(@task) + 1]
			next_task.order -= 1
			next_task.save!
			@task.order += 1
			@task.save!
		end
	end

	private

	def task_params
		params.require(:task).permit(:title, :deadline, :list_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_valid_user!, except: [:show, :show_list_form]		
	before_action :reset_session, except: [:show, :show_list_form]

	respond_to :html
	respond_to :js

	def index
		redirect_to root_path
	end

	def show
		flash.clear
		respond_with(@user)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:success] = 'User has been created. Please, log in'
			redirect_to login_path
		else
			render :new
		end
	end

	def show_list_form
		@user = User.find(params[:id])
		respond_with(@user)
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) : "Task Manager" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://afeld.github.io/emoji-css/emoji.css", media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_edit_list_form.html.erb
<%= form_with(model: @list, remote: true, class: "edit_list_form") do |form| %>
	<div class="input-group">
		<%= form.label :title, class: 'sr-only' %>
		<%= form.text_field :title, class: 'form-control', title: 'List title', placeholder: 'TODO list title', required: true  %>
		<div class="input-group-append">
			<%= form.hidden_field :user_id, :value => @list.user_id %>
			<%= form.submit "Save List", :disable_with => 'Saving...', class: 'btn btn-primary' %>
		</div>
	</div>
	<%- if flash[:error] %>
		<% flash[:error].each do |msg| %>
	    	<small class="form-text text-danger">
				<%= msg %>
	    	</small>
		<% end %>
    <% end %>
<% end %>

app/views/lists/_edit_list_form_error.js.erb
$( "div#<%= dom_id(@list) %> div.card-header > .edit_list_form" ).replaceWith('<%= j render :partial => "edit_list_form" %>');

app/views/lists/_list.html.erb
<div class="list-wrap">
  <%= div_for list, class: 'card' do %>
      <div class='card-header'>
          <h4 class="navbar-text"><%= list.title %></h4>
        <div class="list-edit navbar-text pl-2">
          <%= link_to edit_list_path(list), class: "icon-link", title: "Edit", remote: true do %>
            <i class="em em-pencil2"></i>
          <% end %> | 
          <%= link_to list_path(list), class: "icon-link", title: "Delete", method: :delete, remote: true, data: { confirm: "Are you sure? All tasks in the list will be also deleted." } do %>
            <i class="em em-wastebasket"></i>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <%= render :partial => 'tasks/form', :locals => {:list => list} %>
      </div>
      <ul class="list-group list-group-flush">
          <% list.tasks.each do |task| %>
            <%= render task %>
          <% end %>
      </ul>
  <% end %>
</div>

app/views/lists/_list_form.html.erb
<%= form_with(model: List.new, remote: true, class: "list_form card mb-5") do |form| %>
	
	<div class="input-group">
		<%= form.label :title, class: 'sr-only' %>
		<%= form.text_field :title, class: "form-control", title: 'List title', placeholder: 'TODO list title', required: true  %>
		<div class="input-group-append">
			<%= form.hidden_field :user_id, :value => user.id %>
			<%= form.submit "Create List", :disable_with => 'Creating...', class: 'btn btn-primary' %>
		</div>
	</div>

	<%- if flash[:error] %>
		<% flash[:error].each do |msg| %>
			<small class="form-text text-danger">
				<%= msg %>
			</small>
		<% end %>
	<% end %>

<% end %>

app/views/lists/_list_form_error.js.erb
$( ".list_form" ).replaceWith('<%= j render :partial => "lists/list_form", :locals => {:user => User.find(params[:list][:user_id])} %>');

app/views/lists/create.js.erb
$( "div#user_<%= j @list.user_id.to_s %> > .list_form" ).before('<%= j render partial: "lists/list", locals: {list: @list} %>');
$( "div#user_<%= j @list.user_id.to_s %> > .list_form" )[0].reset();
$( "div#user_<%= j @list.user_id.to_s %> > .list_form" ).remove();
$( ".list-add-btn" ).show();

app/views/lists/destroy.js.erb
$( "div#<%= dom_id(@list) %>" ).parent().hide();

app/views/lists/edit.js.erb
$( "div#<%= dom_id(@list) %> div.card-header > h4" ).replaceWith('<%= j render :partial => "edit_list_form" %>');
$( "div#<%= dom_id(@list) %> div.card-header > .list-edit" ).hide();

app/views/lists/update.js.erb
$( "div#<%= dom_id(@list) %> div.card-header > .edit_list_form" ).replaceWith(' <h4 class="navbar-text"><%= @list.title %></h4> ');
$( "div#<%= dom_id(@list) %> div.card-header > .list-edit" ).show();

app/views/tasks/_edit_form.html.erb
<%= form_with(model: @task, remote: true, class: "edit_task_form col-md-12", id: "task_#{@task.id}") do |form| %>
	<%= form.label :title, class: 'sr-only' %>
	<div class="input-group">
		<%= form.text_field :title, id: "task#{@task.id}_title", class: 'form-control', title: 'Task title', required: true %>
		<div class="input-group-append">
			<div class="input-group input-group-prepend">
				<%= form.label :deadline, for: "task#{@task.id}_deadline", class: 'sr-only' %>
				<%= form.text_field :deadline, id: "task#{@task.id}_deadline", class: 'form-control', title: 'Deadline', :type => "date" %>
				<%= form.hidden_field :list_id, id: "task#{@task.id}_list_id", :value => @task.list_id %>
			</div>
		<%= form.submit "Save Task", :disable_with => 'Saving...', class: 'btn btn-primary' %>
		</div>
	</div>
	<%- if flash[:error] %>
		<% flash[:error].each do |msg| %>
			<small class="form-text text-danger">
				<%= msg %>
			</small>
		<% end %>
	<% end %>	
<% end %>

app/views/tasks/_edit_form_error.js.erb
$( "form#task_<%= @task.id %>" ).replaceWith('<%= j render :partial => "tasks/edit_form" %>');

app/views/tasks/_form.html.erb
<%= form_with(model: Task.new, remote: true, class: "task_form col-md-12") do |form| %>
	<%= form.label :title, class: 'sr-only' %>
	<div class="input-group">
		<%= form.text_field :title, id: "list#{list.id}_task_title", class: 'form-control', title: 'Task title', placeholder: 'Start typing here to create a task...', required: true %>
		<div class="input-group-append">
			<div class="input-group input-group-prepend">
				<%= form.label :deadline, for: "list#{list.id}_task_deadline", class: 'sr-only' %>
				<%= form.text_field :deadline, id: "list#{list.id}_task_deadline", class: 'form-control', title: 'Deadline', :type => "date" %>
				<%= form.hidden_field :list_id, id: "list#{list.id}_task_list_id", :value => list.id %>
			</div>
				<%= form.submit "Create Task", :disable_with => 'Creating...', class: 'btn btn-primary' %>
		</div>
	</div>
	<%- if flash[:error] %>
		<% flash[:error].each do |msg| %>
			<small class="form-text text-danger">
				<%= msg %>
			</small>
		<% end %>
	<% end %>
<% end %>

app/views/tasks/_form_error.js.erb
$( "div#list_<%= params[:task][:list_id] %> > .card-body > .task_form" ).replaceWith('<%= j render :partial => "tasks/form", :locals => {:list => List.find(params[:task][:list_id])} %>');

app/views/tasks/_task.html.erb
<li class="list-group-item">
	<%= div_for(task, class: "#{task.done ? 'done' : 'in_progress'}" + " row col-md-12") do %>
		<div class='col-md-2'>
			<%- if task.done %>
				<%= link_to in_progress_path(task), class: "icon-link", remote: true do %>
					<i class="em em-ballot_box_with_check"></i>
				<% end %>
			<% else %>
				<%= link_to done_path(task), class: "icon-link", remote: true do %>
					<i class="em em-black_square_for_stop"></i>
				<% end %>
			<% end %>
		</div>
		<div class='task-title col-md-6'>
			<%= task.title %>  
		</div>
		<div class='col-md-2'>
			<%- if task.deadline %>
				<i class="em em-calendar"></i> <%= task.deadline.to_date %>
			<% end %>	
		</div>	
		<div class='col-md-2'>
			<%= link_to order_up_path(task), class: "icon-link", title: "Up", remote: true do %>
				<i class="em em-arrow_up"></i>
			<% end %>
			<%= link_to order_down_path(task), class: "icon-link", title: "Down", remote: true do %>
				<i class="em em-arrow_down"></i>
			<% end %> | 
			<%= link_to edit_task_path(task), class: "icon-link", title: "Edit", remote: true do %>
				<i class="em em-pencil2"></i>
			<% end %> | 
			<%= link_to task_path(task), class: "icon-link", title: "Delete", method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
				<i class="em em-wastebasket"></i>
			<% end %>
		</div>
	<% end %>
</li>

app/views/tasks/create.js.erb
$( "div#list_<%= j @task.list_id.to_s %> > ul" ).append('<%= j render partial: "task", locals: {task: @task} %>');
$( "div#list_<%= j @task.list_id.to_s %> > .card-body > .task_form" )[0].reset();
$( ".task_form > small.text-danger" ).remove();

app/views/tasks/destroy.js.erb
$( "div#<%= dom_id(@task) %>" ).parent().hide();

app/views/tasks/done.js.erb
$( "div#<%= dom_id(@task) %>" ).parent().replaceWith('<%= j render partial: "task", locals: {task: @task} %>');

app/views/tasks/edit.js.erb
$( "div#<%= dom_id(@task) %>" ).replaceWith('<%= j render :partial => "edit_form" %>');

app/views/tasks/in_progress.js.erb
$( "div#<%= dom_id(@task) %>" ).parent().replaceWith('<%= j render partial: "task", locals: {task: @task} %>');

app/views/tasks/order_down.js.erb
$( "div#list_<%= @task.list_id %>" ).parent().replaceWith('<%= j render partial: "lists/list", locals: {list: List.find(@task.list_id)} %>');

app/views/tasks/order_up.js.erb
$( "div#list_<%= @task.list_id %>" ).parent().replaceWith('<%= j render partial: "lists/list", locals: {list: List.find(@task.list_id)} %>');

app/views/tasks/update.js.erb
$("form#task_<%= @task.id %>").parent().replaceWith('<%= j render partial: "task", locals: {task: @task} %>');

app/views/users/new.html.erb
<% content_for(:html_title) { 'Task Manager - Sign up' } %>

<div class="flex_center">
	<%= form_for @user, html: {class: "new_user text-center"} do |f| %>
	<p>Create a new account using the form below. All fields are required.</p>
		<h3>Sign Up</h3>
		<div class="form-group">
			<%= f.label :username, class: 'sr-only' %>
			<%= f.text_field :username, class: "form-control #{@user.errors.any? ? 'is-invalid' : ''}", placeholder: 'Username', required: true, autofocus: true %>
		</div>
		<div class="form-group">
			<%= f.label :password, class: 'sr-only' %>
			<%= f.password_field :password, class: "form-control #{@user.errors.any? ? 'is-invalid' : ''}", placeholder: 'Password', required: true %>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, class: 'sr-only' %>
			<%= f.password_field :password_confirmation, class: "form-control #{@user.errors.any? ? 'is-invalid' : ''}", placeholder: 'Confirm Password', required: true %>
	    	<%- if @user.errors.any? %>
				<% @user.errors.full_messages.each do |msg| %>
	    			<div class="invalid-feedback text-left">
						<%= msg %>
	    			</div>
				<% end %>
	    	<% end %>
		</div>
		<%= f.submit "Sign Up", class: 'btn btn-lg btn-primary btn-block' %>
		<p class='mt-2'>
			Have an account? <%= link_to 'Click here to log in.', login_path %>
		</p>
	<% end %>
</div>

app/views/users/show.html.erb
<nav class="navbar">
      <span class="navbar-text ml-md-auto">
        Welcome, <%= @user.username %>!
      </span>
    <div class="navbar-nav px-3">
        <%= link_to 'Log out', logout_path, class: "nav-item btn btn-outline-secondary" %>
    </div>
</nav>
<%= div_for @user, class: 'container' do %>
    <% @user.lists.each do |list| %>
      <%= render :partial => 'lists/list', :locals => {:list => list} %>
    <% end %>
  <div class="list-add-btn text-center mb-5">

    <%- if @user.lists.empty? %>
      <h4 class="welcome-text pb-3 pt-5">Click the button below to create your first TODO list</h4>
    <% end %>

    <%= link_to "Add TODO List", show_list_form_path(@user), remote: true, class: 'btn btn-lg btn-primary' %>
  </div>
<% end %>

  

app/views/users/show_list_form.js.erb
$( ".list-add-btn" ).before('<%= j render :partial => "lists/list_form", :locals => {:user => @user} %>');
$( ".welcome-text" ).remove();
$( ".list-add-btn" ).hide();